export default{
    "id": 2,
    "sectionName": "Home",
    "users_permissions_user": null,
    "published_at": "2020-11-23T23:34:50.386Z",
    "created_at": "2020-11-23T23:19:05.034Z",
    "updated_at": "2021-01-23T12:02:37.984Z",
    "content": [
        {
            "__component": "page.landing",
            "id": 1,
            "LandingTitle": "Home Page",
            "LandingButtonYesOrNot": true,
            "LandingButtonText": "Scopri di più",
            "LandingPageDescription": "\"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ",
            "LandingPageBackground": {
                "id": 5,
                "name": "PP-benessere.jpg",
                "alternativeText": "",
                "caption": "",
                "width": 800,
                "height": 530,
                "formats": {
                    "thumbnail": {
                        "name": "thumbnail_PP-benessere.jpg",
                        "hash": "thumbnail_PP_benessere_cdac46d231",
                        "ext": ".jpg",
                        "mime": "image/jpeg",
                        "width": 235,
                        "height": 156,
                        "size": 7.23,
                        "path": null,
                        "url": "/uploads/thumbnail_PP_benessere_cdac46d231.jpg"
                    },
                    "medium": {
                        "name": "medium_PP-benessere.jpg",
                        "hash": "medium_PP_benessere_cdac46d231",
                        "ext": ".jpg",
                        "mime": "image/jpeg",
                        "width": 750,
                        "height": 497,
                        "size": 39.34,
                        "path": null,
                        "url": "/uploads/medium_PP_benessere_cdac46d231.jpg"
                    },
                    "small": {
                        "name": "small_PP-benessere.jpg",
                        "hash": "small_PP_benessere_cdac46d231",
                        "ext": ".jpg",
                        "mime": "image/jpeg",
                        "width": 500,
                        "height": 331,
                        "size": 21.71,
                        "path": null,
                        "url": "/uploads/small_PP_benessere_cdac46d231.jpg"
                    }
                },
                "hash": "PP_benessere_cdac46d231",
                "ext": ".jpg",
                "mime": "image/jpeg",
                "size": 43.16,
                "url": "https://i1.wp.com/www.sociosfera.it/sociosfera/wp-content/uploads/2020/04/featured-stress-operatori-news-ok.jpg?fit=825%2C354&ssl=1",
                "previewUrl": null,
                "provider": "local",
                "provider_metadata": null,
                "created_at": "2020-12-23T22:20:03.894Z",
                "updated_at": "2020-12-23T22:20:03.930Z"
            }
        },
        {
            "__component": "page.frame-with-background",
            "id": 1,
            "frameTitle": "Frame con sfondo",
            "frameDescription": "London. Michaelmas term lately over, and the Lord Chancellor sitting in Lincoln's Inn Hall. Implacable November weather. As much mud in the streets as if the waters had but newly retired from the face of the earth, and it would not be wonderful to meet a Megalosaurus, forty feet long or so, waddling like an elephantine lizard up Holborn Hill.",
            "frameSize": "Large",
            "frameTextPosition": "Left",
            "frameButtonYesOrNot": null,
            "frameButtonText": null,
            "frameButtonGoesTo": null,
            "frameSecondaryImageYesOrNot": null,
            "frameBackgroundImage": {
                "id": 1,
                "name": "photo-1489549132488-d00b7eee80f1.jpg",
                "alternativeText": "",
                "caption": "",
                "width": 634,
                "height": 951,
                "formats": {
                    "thumbnail": {
                        "name": "thumbnail_photo-1489549132488-d00b7eee80f1.jpg",
                        "hash": "thumbnail_photo_1489549132488_d00b7eee80f1_ef6284d992",
                        "ext": ".jpg",
                        "mime": "image/jpeg",
                        "width": 104,
                        "height": 156,
                        "size": 1.27,
                        "path": null,
                        "url": "/uploads/thumbnail_photo_1489549132488_d00b7eee80f1_ef6284d992.jpg"
                    },
                    "medium": {
                        "name": "medium_photo-1489549132488-d00b7eee80f1.jpg",
                        "hash": "medium_photo_1489549132488_d00b7eee80f1_ef6284d992",
                        "ext": ".jpg",
                        "mime": "image/jpeg",
                        "width": 500,
                        "height": 750,
                        "size": 14.94,
                        "path": null,
                        "url": "/uploads/medium_photo_1489549132488_d00b7eee80f1_ef6284d992.jpg"
                    },
                    "small": {
                        "name": "small_photo-1489549132488-d00b7eee80f1.jpg",
                        "hash": "small_photo_1489549132488_d00b7eee80f1_ef6284d992",
                        "ext": ".jpg",
                        "mime": "image/jpeg",
                        "width": 333,
                        "height": 500,
                        "size": 7.5,
                        "path": null,
                        "url": "/uploads/small_photo_1489549132488_d00b7eee80f1_ef6284d992.jpg"
                    }
                },
                "hash": "photo_1489549132488_d00b7eee80f1_ef6284d992",
                "ext": ".jpg",
                "mime": "image/jpeg",
                "size": 20.9,
                "url": "https://www.anticobenessere.it/wp-content/uploads/2020/11/percorso-benessere.jpg",
                "previewUrl": null,
                "provider": "local",
                "provider_metadata": null,
                "created_at": "2020-11-24T00:26:22.961Z",
                "updated_at": "2020-11-24T00:26:22.988Z"
            },
            "frameSecondaryImage": null
        },
        {
            "__component": "page.services-description",
            "id": 1,
            "serviceBoxTitle": "Servizi",
            "serviceImage": [
                {
                    "id": 2,
                    "name": "image.jpg",
                    "alternativeText": "",
                    "caption": "",
                    "width": 675,
                    "height": 900,
                    "formats": {
                        "thumbnail": {
                            "name": "thumbnail_image.jpg",
                            "hash": "thumbnail_image_61637723a7",
                            "ext": ".jpg",
                            "mime": "image/jpeg",
                            "width": 117,
                            "height": 156,
                            "size": 1.23,
                            "path": null,
                            "url": "/uploads/thumbnail_image_61637723a7.jpg"
                        },
                        "medium": {
                            "name": "medium_image.jpg",
                            "hash": "medium_image_61637723a7",
                            "ext": ".jpg",
                            "mime": "image/jpeg",
                            "width": 563,
                            "height": 750,
                            "size": 10.49,
                            "path": null,
                            "url": "/uploads/medium_image_61637723a7.jpg"
                        },
                        "small": {
                            "name": "small_image.jpg",
                            "hash": "small_image_61637723a7",
                            "ext": ".jpg",
                            "mime": "image/jpeg",
                            "width": 375,
                            "height": 500,
                            "size": 5.74,
                            "path": null,
                            "url": "/uploads/small_image_61637723a7.jpg"
                        }
                    },
                    "hash": "image_61637723a7",
                    "ext": ".jpg",
                    "mime": "image/jpeg",
                    "size": 13.8,
                    "url": "https://www.cralgtt.it/wp-content/uploads/2017/11/Cral-Gtt-la-fabbrica-del-benessere-convenzione-750x450.jpg",
                    "previewUrl": null,
                    "provider": "local",
                    "provider_metadata": null,
                    "created_at": "2020-11-24T00:26:42.738Z",
                    "updated_at": "2020-11-24T00:26:42.766Z"
                },
                {
                    "id": 1,
                    "name": "photo-1489549132488-d00b7eee80f1.jpg",
                    "alternativeText": "",
                    "caption": "",
                    "width": 634,
                    "height": 951,
                    "formats": {
                        "thumbnail": {
                            "name": "thumbnail_photo-1489549132488-d00b7eee80f1.jpg",
                            "hash": "thumbnail_photo_1489549132488_d00b7eee80f1_ef6284d992",
                            "ext": ".jpg",
                            "mime": "image/jpeg",
                            "width": 104,
                            "height": 156,
                            "size": 1.27,
                            "path": null,
                            "url": "/uploads/thumbnail_photo_1489549132488_d00b7eee80f1_ef6284d992.jpg"
                        },
                        "medium": {
                            "name": "medium_photo-1489549132488-d00b7eee80f1.jpg",
                            "hash": "medium_photo_1489549132488_d00b7eee80f1_ef6284d992",
                            "ext": ".jpg",
                            "mime": "image/jpeg",
                            "width": 500,
                            "height": 750,
                            "size": 14.94,
                            "path": null,
                            "url": "/uploads/medium_photo_1489549132488_d00b7eee80f1_ef6284d992.jpg"
                        },
                        "small": {
                            "name": "small_photo-1489549132488-d00b7eee80f1.jpg",
                            "hash": "small_photo_1489549132488_d00b7eee80f1_ef6284d992",
                            "ext": ".jpg",
                            "mime": "image/jpeg",
                            "width": 333,
                            "height": 500,
                            "size": 7.5,
                            "path": null,
                            "url": "/uploads/small_photo_1489549132488_d00b7eee80f1_ef6284d992.jpg"
                        }
                    },
                    "hash": "photo_1489549132488_d00b7eee80f1_ef6284d992",
                    "ext": ".jpg",
                    "mime": "image/jpeg",
                    "size": 20.9,
                    "url": "/uploads/photo_1489549132488_d00b7eee80f1_ef6284d992.jpg",
                    "previewUrl": null,
                    "provider": "local",
                    "provider_metadata": null,
                    "created_at": "2020-11-24T00:26:22.961Z",
                    "updated_at": "2020-11-24T00:26:22.988Z"
                },
                {
                    "id": 3,
                    "name": "download.jpg",
                    "alternativeText": "",
                    "caption": "",
                    "width": 196,
                    "height": 257,
                    "formats": {
                        "thumbnail": {
                            "name": "thumbnail_download.jpg",
                            "hash": "thumbnail_download_dbbe5f3985",
                            "ext": ".jpg",
                            "mime": "image/jpeg",
                            "width": 119,
                            "height": 156,
                            "size": 4.1,
                            "path": null,
                            "url": "/uploads/thumbnail_download_dbbe5f3985.jpg"
                        }
                    },
                    "hash": "download_dbbe5f3985",
                    "ext": ".jpg",
                    "mime": "image/jpeg",
                    "size": 5.73,
                    "url": "https://www.cralgtt.it/wp-content/uploads/2017/11/Cral-Gtt-la-fabbrica-del-benessere-convenzione-750x450.jpg",
                    "previewUrl": null,
                    "provider": "local",
                    "provider_metadata": null,
                    "created_at": "2020-12-23T22:16:22.954Z",
                    "updated_at": "2020-12-23T22:16:23.004Z"
                },
                {
                    "id": 4,
                    "name": "sign.jpg",
                    "alternativeText": "",
                    "caption": "",
                    "width": 4000,
                    "height": 3000,
                    "formats": {
                        "thumbnail": {
                            "name": "thumbnail_sign.jpg",
                            "hash": "thumbnail_sign_36c0f0f4d2",
                            "ext": ".jpg",
                            "mime": "image/jpeg",
                            "width": 208,
                            "height": 156,
                            "size": 2.38,
                            "path": null,
                            "url": "/uploads/thumbnail_sign_36c0f0f4d2.jpg"
                        },
                        "large": {
                            "name": "large_sign.jpg",
                            "hash": "large_sign_36c0f0f4d2",
                            "ext": ".jpg",
                            "mime": "image/jpeg",
                            "width": 1000,
                            "height": 750,
                            "size": 26.5,
                            "path": null,
                            "url": "/uploads/large_sign_36c0f0f4d2.jpg"
                        },
                        "medium": {
                            "name": "medium_sign.jpg",
                            "hash": "medium_sign_36c0f0f4d2",
                            "ext": ".jpg",
                            "mime": "image/jpeg",
                            "width": 750,
                            "height": 563,
                            "size": 16.73,
                            "path": null,
                            "url": "/uploads/medium_sign_36c0f0f4d2.jpg"
                        },
                        "small": {
                            "name": "small_sign.jpg",
                            "hash": "small_sign_36c0f0f4d2",
                            "ext": ".jpg",
                            "mime": "image/jpeg",
                            "width": 500,
                            "height": 375,
                            "size": 9.15,
                            "path": null,
                            "url": "/uploads/small_sign_36c0f0f4d2.jpg"
                        }
                    },
                    "hash": "sign_36c0f0f4d2",
                    "ext": ".jpg",
                    "mime": "image/jpeg",
                    "size": 272.11,
                    "url": "https://www.cralgtt.it/wp-content/uploads/2017/11/Cral-Gtt-la-fabbrica-del-benessere-convenzione-750x450.jpg",
                    "previewUrl": null,
                    "provider": "local",
                    "provider_metadata": null,
                    "created_at": "2020-12-23T22:16:23.576Z",
                    "updated_at": "2020-12-23T22:16:23.603Z"
                }
            ]
        },
        {
            "__component": "page.frame-with-background",
            "id": 2,
            "frameTitle": "Lorem Ipsum small",
            "frameDescription": "\"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?\"",
            "frameSize": "Small",
            "frameTextPosition": "Left",
            "frameButtonYesOrNot": null,
            "frameButtonText": null,
            "frameButtonGoesTo": null,
            "frameSecondaryImageYesOrNot": null,
            "frameBackgroundImage": {
                "id": 2,
                "name": "image.jpg",
                "alternativeText": "",
                "caption": "",
                "width": 675,
                "height": 900,
                "formats": {
                    "thumbnail": {
                        "name": "thumbnail_image.jpg",
                        "hash": "thumbnail_image_61637723a7",
                        "ext": ".jpg",
                        "mime": "image/jpeg",
                        "width": 117,
                        "height": 156,
                        "size": 1.23,
                        "path": null,
                        "url": "/uploads/thumbnail_image_61637723a7.jpg"
                    },
                    "medium": {
                        "name": "medium_image.jpg",
                        "hash": "medium_image_61637723a7",
                        "ext": ".jpg",
                        "mime": "image/jpeg",
                        "width": 563,
                        "height": 750,
                        "size": 10.49,
                        "path": null,
                        "url": "/uploads/medium_image_61637723a7.jpg"
                    },
                    "small": {
                        "name": "small_image.jpg",
                        "hash": "small_image_61637723a7",
                        "ext": ".jpg",
                        "mime": "image/jpeg",
                        "width": 375,
                        "height": 500,
                        "size": 5.74,
                        "path": null,
                        "url": "/uploads/small_image_61637723a7.jpg"
                    }
                },
                "hash": "image_61637723a7",
                "ext": ".jpg",
                "mime": "image/jpeg",
                "size": 13.8,
                "url": "/uploads/image_61637723a7.jpg",
                "previewUrl": null,
                "provider": "local",
                "provider_metadata": null,
                "created_at": "2020-11-24T00:26:42.738Z",
                "updated_at": "2020-11-24T00:26:42.766Z"
            },
            "frameSecondaryImage": null
        },
        {
            "__component": "page.frame-with-background",
            "id": 5,
            "frameTitle": "Frame con button large",
            "frameDescription": "\"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?\"",
            "frameSize": "Large",
            "frameTextPosition": "Right",
            "frameButtonYesOrNot": true,
            "frameButtonText": "Chi sono",
            "frameButtonGoesTo": "about",
            "frameSecondaryImageYesOrNot": null,
            "frameBackgroundImage": {
                "id": 5,
                "name": "PP-benessere.jpg",
                "alternativeText": "",
                "caption": "",
                "width": 800,
                "height": 530,
                "formats": {
                    "thumbnail": {
                        "name": "thumbnail_PP-benessere.jpg",
                        "hash": "thumbnail_PP_benessere_cdac46d231",
                        "ext": ".jpg",
                        "mime": "image/jpeg",
                        "width": 235,
                        "height": 156,
                        "size": 7.23,
                        "path": null,
                        "url": "/uploads/thumbnail_PP_benessere_cdac46d231.jpg"
                    },
                    "medium": {
                        "name": "medium_PP-benessere.jpg",
                        "hash": "medium_PP_benessere_cdac46d231",
                        "ext": ".jpg",
                        "mime": "image/jpeg",
                        "width": 750,
                        "height": 497,
                        "size": 39.34,
                        "path": null,
                        "url": "/uploads/medium_PP_benessere_cdac46d231.jpg"
                    },
                    "small": {
                        "name": "small_PP-benessere.jpg",
                        "hash": "small_PP_benessere_cdac46d231",
                        "ext": ".jpg",
                        "mime": "image/jpeg",
                        "width": 500,
                        "height": 331,
                        "size": 21.71,
                        "path": null,
                        "url": "/uploads/small_PP_benessere_cdac46d231.jpg"
                    }
                },
                "hash": "PP_benessere_cdac46d231",
                "ext": ".jpg",
                "mime": "image/jpeg",
                "size": 43.16,
                "url": "https://www.fondoasim.it/wp-content/uploads/2019/04/Indicatori-di-benessere-cover.jpg",
                "previewUrl": null,
                "provider": "local",
                "provider_metadata": null,
                "created_at": "2020-12-23T22:20:03.894Z",
                "updated_at": "2020-12-23T22:20:03.930Z"
            },
            "frameSecondaryImage": null
        },
        {
            "__component": "page.frame-with-background",
            "id": 6,
            "frameTitle": "Frame con seconda immagine small",
            "frameDescription": "\"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?\"",
            "frameSize": "Small",
            "frameTextPosition": "Right",
            "frameButtonYesOrNot": null,
            "frameButtonText": null,
            "frameButtonGoesTo": null,
            "frameSecondaryImageYesOrNot": true,
            "frameBackgroundImage": {
                "id": 5,
                "name": "PP-benessere.jpg",
                "alternativeText": "",
                "caption": "",
                "width": 800,
                "height": 530,
                "formats": {
                    "thumbnail": {
                        "name": "thumbnail_PP-benessere.jpg",
                        "hash": "thumbnail_PP_benessere_cdac46d231",
                        "ext": ".jpg",
                        "mime": "image/jpeg",
                        "width": 235,
                        "height": 156,
                        "size": 7.23,
                        "path": null,
                        "url": "/uploads/thumbnail_PP_benessere_cdac46d231.jpg"
                    },
                    "medium": {
                        "name": "medium_PP-benessere.jpg",
                        "hash": "medium_PP_benessere_cdac46d231",
                        "ext": ".jpg",
                        "mime": "image/jpeg",
                        "width": 750,
                        "height": 497,
                        "size": 39.34,
                        "path": null,
                        "url": "/uploads/medium_PP_benessere_cdac46d231.jpg"
                    },
                    "small": {
                        "name": "small_PP-benessere.jpg",
                        "hash": "small_PP_benessere_cdac46d231",
                        "ext": ".jpg",
                        "mime": "image/jpeg",
                        "width": 500,
                        "height": 331,
                        "size": 21.71,
                        "path": null,
                        "url": "/uploads/small_PP_benessere_cdac46d231.jpg"
                    }
                },
                "hash": "PP_benessere_cdac46d231",
                "ext": ".jpg",
                "mime": "image/jpeg",
                "size": 43.16,
                "url": "https://admin.abc.sm/image_thumb_abcweb.php?img=https://admin.abc.sm/img/gallery/upload/3564/img_lastminute_24835.jpg&w=600&h=350&o=0",
                "previewUrl": null,
                "provider": "local",
                "provider_metadata": null,
                "created_at": "2020-12-23T22:20:03.894Z",
                "updated_at": "2020-12-23T22:20:03.930Z"
            },
            "frameSecondaryImage": {
                "id": 5,
                "name": "PP-benessere.jpg",
                "alternativeText": "",
                "caption": "",
                "width": 800,
                "height": 530,
                "formats": {
                    "thumbnail": {
                        "name": "thumbnail_PP-benessere.jpg",
                        "hash": "thumbnail_PP_benessere_cdac46d231",
                        "ext": ".jpg",
                        "mime": "image/jpeg",
                        "width": 235,
                        "height": 156,
                        "size": 7.23,
                        "path": null,
                        "url": "/uploads/thumbnail_PP_benessere_cdac46d231.jpg"
                    },
                    "medium": {
                        "name": "medium_PP-benessere.jpg",
                        "hash": "medium_PP_benessere_cdac46d231",
                        "ext": ".jpg",
                        "mime": "image/jpeg",
                        "width": 750,
                        "height": 497,
                        "size": 39.34,
                        "path": null,
                        "url": "/uploads/medium_PP_benessere_cdac46d231.jpg"
                    },
                    "small": {
                        "name": "small_PP-benessere.jpg",
                        "hash": "small_PP_benessere_cdac46d231",
                        "ext": ".jpg",
                        "mime": "image/jpeg",
                        "width": 500,
                        "height": 331,
                        "size": 21.71,
                        "path": null,
                        "url": "/uploads/small_PP_benessere_cdac46d231.jpg"
                    }
                },
                "hash": "PP_benessere_cdac46d231",
                "ext": ".jpg",
                "mime": "image/jpeg",
                "size": 43.16,
                "url": "https://www.noisiamofuturo.it/wp-content/uploads/2017/12/Foto-articolo.jpg",
                "previewUrl": null,
                "provider": "local",
                "provider_metadata": null,
                "created_at": "2020-12-23T22:20:03.894Z",
                "updated_at": "2020-12-23T22:20:03.930Z"
            }
        },
        {
            "__component": "page.frame-with-background",
            "id": 7,
            "frameTitle": "frame button e seconda large",
            "frameDescription": "antium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum f",
            "frameSize": "Large",
            "frameTextPosition": "Left",
            "frameButtonYesOrNot": true,
            "frameButtonText": "vai a mindfulness",
            "frameButtonGoesTo": "mindufulness",
            "frameSecondaryImageYesOrNot": true,
            "frameBackgroundImage": {
                "id": 5,
                "name": "PP-benessere.jpg",
                "alternativeText": "",
                "caption": "",
                "width": 800,
                "height": 530,
                "formats": {
                    "thumbnail": {
                        "name": "thumbnail_PP-benessere.jpg",
                        "hash": "thumbnail_PP_benessere_cdac46d231",
                        "ext": ".jpg",
                        "mime": "image/jpeg",
                        "width": 235,
                        "height": 156,
                        "size": 7.23,
                        "path": null,
                        "url": "/uploads/thumbnail_PP_benessere_cdac46d231.jpg"
                    },
                    "medium": {
                        "name": "medium_PP-benessere.jpg",
                        "hash": "medium_PP_benessere_cdac46d231",
                        "ext": ".jpg",
                        "mime": "image/jpeg",
                        "width": 750,
                        "height": 497,
                        "size": 39.34,
                        "path": null,
                        "url": "/uploads/medium_PP_benessere_cdac46d231.jpg"
                    },
                    "small": {
                        "name": "small_PP-benessere.jpg",
                        "hash": "small_PP_benessere_cdac46d231",
                        "ext": ".jpg",
                        "mime": "image/jpeg",
                        "width": 500,
                        "height": 331,
                        "size": 21.71,
                        "path": null,
                        "url": "/uploads/small_PP_benessere_cdac46d231.jpg"
                    }
                },
                "hash": "PP_benessere_cdac46d231",
                "ext": ".jpg",
                "mime": "image/jpeg",
                "size": 43.16,
                "url": "https://www.noisiamofuturo.it/wp-content/uploads/2017/12/Foto-articolo.jpg",
                "previewUrl": null,
                "provider": "local",
                "provider_metadata": null,
                "created_at": "2020-12-23T22:20:03.894Z",
                "updated_at": "2020-12-23T22:20:03.930Z"
            },
            "frameSecondaryImage": {
                "id": 5,
                "name": "PP-benessere.jpg",
                "alternativeText": "",
                "caption": "",
                "width": 800,
                "height": 530,
                "formats": {
                    "thumbnail": {
                        "name": "thumbnail_PP-benessere.jpg",
                        "hash": "thumbnail_PP_benessere_cdac46d231",
                        "ext": ".jpg",
                        "mime": "image/jpeg",
                        "width": 235,
                        "height": 156,
                        "size": 7.23,
                        "path": null,
                        "url": "/uploads/thumbnail_PP_benessere_cdac46d231.jpg"
                    },
                    "medium": {
                        "name": "medium_PP-benessere.jpg",
                        "hash": "medium_PP_benessere_cdac46d231",
                        "ext": ".jpg",
                        "mime": "image/jpeg",
                        "width": 750,
                        "height": 497,
                        "size": 39.34,
                        "path": null,
                        "url": "/uploads/medium_PP_benessere_cdac46d231.jpg"
                    },
                    "small": {
                        "name": "small_PP-benessere.jpg",
                        "hash": "small_PP_benessere_cdac46d231",
                        "ext": ".jpg",
                        "mime": "image/jpeg",
                        "width": 500,
                        "height": 331,
                        "size": 21.71,
                        "path": null,
                        "url": "/uploads/small_PP_benessere_cdac46d231.jpg"
                    }
                },
                "hash": "PP_benessere_cdac46d231",
                "ext": ".jpg",
                "mime": "image/jpeg",
                "size": 43.16,
                "url": "https://www.salutelab.it/wp-content/uploads/2020/12/benessere.jpg",
                "previewUrl": null,
                "provider": "local",
                "provider_metadata": null,
                "created_at": "2020-12-23T22:20:03.894Z",
                "updated_at": "2020-12-23T22:20:03.930Z"
            }
        }
    ]
}
